// Code generated by protoc-gen-go. DO NOT EDIT.
// source: vote.proto

package pbVote

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type VoteRequest_State int32

const (
	VoteRequest_Unlike VoteRequest_State = 0
	VoteRequest_Cancel VoteRequest_State = 1
	VoteRequest_Like   VoteRequest_State = 2
)

var VoteRequest_State_name = map[int32]string{
	0: "Unlike",
	1: "Cancel",
	2: "Like",
}

var VoteRequest_State_value = map[string]int32{
	"Unlike": 0,
	"Cancel": 1,
	"Like":   2,
}

func (x VoteRequest_State) String() string {
	return proto.EnumName(VoteRequest_State_name, int32(x))
}

func (VoteRequest_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_21d31c94b62a6ac7, []int{0, 0}
}

// 投票
type VoteRequest struct {
	PostID               int64             `protobuf:"varint,1,opt,name=PostID,proto3" json:"PostID,omitempty" validate:"required"`
	Mode                 VoteRequest_State `protobuf:"varint,2,opt,name=Mode,proto3,enum=pbVote.VoteRequest_State" json:"Mode,omitempty" validate:"oneof=0 1 2"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *VoteRequest) Reset()         { *m = VoteRequest{} }
func (m *VoteRequest) String() string { return proto.CompactTextString(m) }
func (*VoteRequest) ProtoMessage()    {}
func (*VoteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_21d31c94b62a6ac7, []int{0}
}

func (m *VoteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoteRequest.Unmarshal(m, b)
}
func (m *VoteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoteRequest.Marshal(b, m, deterministic)
}
func (m *VoteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoteRequest.Merge(m, src)
}
func (m *VoteRequest) XXX_Size() int {
	return xxx_messageInfo_VoteRequest.Size(m)
}
func (m *VoteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VoteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VoteRequest proto.InternalMessageInfo

func (m *VoteRequest) GetPostID() int64 {
	if m != nil {
		return m.PostID
	}
	return 0
}

func (m *VoteRequest) GetMode() VoteRequest_State {
	if m != nil {
		return m.Mode
	}
	return VoteRequest_Unlike
}

// ======== Response ========
type Response struct {
	// 响应
	Code                 int32             `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg                  string            `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	Data                 map[string]string `protobuf:"bytes,3,rep,name=Data,proto3" json:"Data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_21d31c94b62a6ac7, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *Response) GetData() map[string]string {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterEnum("pbVote.VoteRequest_State", VoteRequest_State_name, VoteRequest_State_value)
	proto.RegisterType((*VoteRequest)(nil), "pbVote.VoteRequest")
	proto.RegisterType((*Response)(nil), "pbVote.Response")
	proto.RegisterMapType((map[string]string)(nil), "pbVote.Response.DataEntry")
}

func init() {
	proto.RegisterFile("vote.proto", fileDescriptor_21d31c94b62a6ac7)
}

var fileDescriptor_21d31c94b62a6ac7 = []byte{
	// 263 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0xbb, 0xf9, 0x47, 0x33, 0x05, 0x09, 0xa3, 0x48, 0xcc, 0x29, 0xe4, 0x14, 0x0f, 0xae,
	0x10, 0x0f, 0x15, 0xaf, 0xad, 0x07, 0xc1, 0x82, 0xac, 0xe8, 0x7d, 0xab, 0x83, 0x48, 0x43, 0x36,
	0x76, 0xb7, 0x85, 0x9e, 0xfc, 0x1c, 0x7e, 0x5b, 0x99, 0x6d, 0x2a, 0x22, 0x9e, 0xe6, 0xbd, 0xd9,
	0x99, 0xf7, 0xdb, 0x5d, 0x80, 0xad, 0x71, 0x24, 0xfb, 0xb5, 0x71, 0x06, 0x93, 0x7e, 0xf9, 0x6c,
	0x1c, 0x55, 0x9f, 0x30, 0xe1, 0xaa, 0xe8, 0x63, 0x43, 0xd6, 0xe1, 0x29, 0x24, 0x0f, 0xc6, 0xba,
	0xbb, 0x79, 0x2e, 0x4a, 0x51, 0x87, 0x6a, 0x70, 0x78, 0x01, 0xd1, 0xc2, 0xbc, 0x52, 0x1e, 0x94,
	0xa2, 0x3e, 0x6a, 0xce, 0xe4, 0x7e, 0x5b, 0xfe, 0x5a, 0x95, 0x8f, 0x4e, 0x3b, 0x52, 0x7e, 0xac,
	0x3a, 0x87, 0xd8, 0x5b, 0x04, 0x48, 0x9e, 0xba, 0xf6, 0x7d, 0x45, 0xd9, 0x88, 0xf5, 0x4c, 0x77,
	0x2f, 0xd4, 0x66, 0x02, 0xc7, 0x10, 0xdd, 0x73, 0x37, 0xa8, 0xbe, 0x04, 0x8c, 0x15, 0xd9, 0xde,
	0x74, 0x96, 0x10, 0x21, 0x9a, 0x31, 0x86, 0xe1, 0xb1, 0xf2, 0x1a, 0x33, 0x08, 0x17, 0xf6, 0xcd,
	0x93, 0x53, 0xc5, 0x12, 0x25, 0x44, 0x73, 0xed, 0x74, 0x1e, 0x96, 0x61, 0x3d, 0x69, 0x8a, 0xc3,
	0x65, 0x0e, 0x29, 0x92, 0x0f, 0x6f, 0x3b, 0xb7, 0xde, 0x29, 0x3f, 0x57, 0x4c, 0x21, 0xfd, 0x69,
	0x71, 0xdc, 0x8a, 0x76, 0x9e, 0x90, 0x2a, 0x96, 0x78, 0x02, 0xf1, 0x56, 0xb7, 0x1b, 0x1a, 0x10,
	0x7b, 0x73, 0x13, 0x5c, 0x8b, 0x66, 0x0a, 0x11, 0x27, 0xe3, 0xe5, 0x50, 0x8f, 0xff, 0x79, 0x77,
	0x91, 0xfd, 0xe5, 0x57, 0xa3, 0x65, 0xe2, 0x3f, 0xf9, 0xea, 0x3b, 0x00, 0x00, 0xff, 0xff, 0xd9,
	0x42, 0x5c, 0x9e, 0x72, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// VoteClient is the client API for Vote service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VoteClient interface {
	Vote(ctx context.Context, in *VoteRequest, opts ...grpc.CallOption) (*Response, error)
}

type voteClient struct {
	cc grpc.ClientConnInterface
}

func NewVoteClient(cc grpc.ClientConnInterface) VoteClient {
	return &voteClient{cc}
}

func (c *voteClient) Vote(ctx context.Context, in *VoteRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/pbVote.Vote/Vote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VoteServer is the server API for Vote service.
type VoteServer interface {
	Vote(context.Context, *VoteRequest) (*Response, error)
}

// UnimplementedVoteServer can be embedded to have forward compatible implementations.
type UnimplementedVoteServer struct {
}

func (*UnimplementedVoteServer) Vote(ctx context.Context, req *VoteRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Vote not implemented")
}

func RegisterVoteServer(s *grpc.Server, srv VoteServer) {
	s.RegisterService(&_Vote_serviceDesc, srv)
}

func _Vote_Vote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VoteServer).Vote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbVote.Vote/Vote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VoteServer).Vote(ctx, req.(*VoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Vote_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pbVote.Vote",
	HandlerType: (*VoteServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Vote",
			Handler:    _Vote_Vote_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vote.proto",
}
