// Code generated by protoc-gen-go. DO NOT EDIT.
// source: post.proto

package pbPost

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 使用枚举获取访问状态 是根据作者还是社区分类访问
type GetPostListRequest_State int32

const (
	GetPostListRequest_Community GetPostListRequest_State = 0
	GetPostListRequest_Author    GetPostListRequest_State = 1
)

var GetPostListRequest_State_name = map[int32]string{
	0: "Community",
	1: "Author",
}

var GetPostListRequest_State_value = map[string]int32{
	"Community": 0,
	"Author":    1,
}

func (x GetPostListRequest_State) String() string {
	return proto.EnumName(GetPostListRequest_State_name, int32(x))
}

func (GetPostListRequest_State) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{2, 0}
}

// 创建帖子
type CreatePostRequest struct {
	//  int64 PostID = 1; // 帖子ID  // Tag: validate:"required,numeric"
	//  int64 AuthorID = 2; // 作者ID // Tag: validate:"required,numeric"
	CommunityID          int64    `protobuf:"varint,1,opt,name=CommunityID,proto3" json:"CommunityID,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=Title,proto3" json:"Title,omitempty" validate:"required"`
	Content              string   `protobuf:"bytes,3,opt,name=Content,proto3" json:"Content,omitempty" validate:"required"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePostRequest) Reset()         { *m = CreatePostRequest{} }
func (m *CreatePostRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePostRequest) ProtoMessage()    {}
func (*CreatePostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{0}
}

func (m *CreatePostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePostRequest.Unmarshal(m, b)
}
func (m *CreatePostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePostRequest.Marshal(b, m, deterministic)
}
func (m *CreatePostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePostRequest.Merge(m, src)
}
func (m *CreatePostRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePostRequest.Size(m)
}
func (m *CreatePostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePostRequest proto.InternalMessageInfo

func (m *CreatePostRequest) GetCommunityID() int64 {
	if m != nil {
		return m.CommunityID
	}
	return 0
}

func (m *CreatePostRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CreatePostRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

// 获取帖子详情
type GetPostDetailRequest struct {
	PostID               int64    `protobuf:"varint,1,opt,name=PostID,proto3" json:"PostID,omitempty" validate:"required"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPostDetailRequest) Reset()         { *m = GetPostDetailRequest{} }
func (m *GetPostDetailRequest) String() string { return proto.CompactTextString(m) }
func (*GetPostDetailRequest) ProtoMessage()    {}
func (*GetPostDetailRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{1}
}

func (m *GetPostDetailRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPostDetailRequest.Unmarshal(m, b)
}
func (m *GetPostDetailRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPostDetailRequest.Marshal(b, m, deterministic)
}
func (m *GetPostDetailRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPostDetailRequest.Merge(m, src)
}
func (m *GetPostDetailRequest) XXX_Size() int {
	return xxx_messageInfo_GetPostDetailRequest.Size(m)
}
func (m *GetPostDetailRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPostDetailRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPostDetailRequest proto.InternalMessageInfo

func (m *GetPostDetailRequest) GetPostID() int64 {
	if m != nil {
		return m.PostID
	}
	return 0
}

// 获取帖子列表
type GetPostListRequest struct {
	Model GetPostListRequest_State `protobuf:"varint,1,opt,name=Model,proto3,enum=pbPost.GetPostListRequest_State" json:"Model,omitempty"`
	// Types that are valid to be assigned to ID:
	//	*GetPostListRequest_CommunityID
	//	*GetPostListRequest_AuthorID
	ID                   isGetPostListRequest_ID `protobuf_oneof:"ID"`
	Page                 int64                   `protobuf:"varint,4,opt,name=Page,proto3" json:"Page,omitempty" validate:"required"`
	Max                  int64                   `protobuf:"varint,5,opt,name=Max,proto3" json:"Max,omitempty" validate:"required"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *GetPostListRequest) Reset()         { *m = GetPostListRequest{} }
func (m *GetPostListRequest) String() string { return proto.CompactTextString(m) }
func (*GetPostListRequest) ProtoMessage()    {}
func (*GetPostListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{2}
}

func (m *GetPostListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPostListRequest.Unmarshal(m, b)
}
func (m *GetPostListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPostListRequest.Marshal(b, m, deterministic)
}
func (m *GetPostListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPostListRequest.Merge(m, src)
}
func (m *GetPostListRequest) XXX_Size() int {
	return xxx_messageInfo_GetPostListRequest.Size(m)
}
func (m *GetPostListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPostListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPostListRequest proto.InternalMessageInfo

func (m *GetPostListRequest) GetModel() GetPostListRequest_State {
	if m != nil {
		return m.Model
	}
	return GetPostListRequest_Community
}

type isGetPostListRequest_ID interface {
	isGetPostListRequest_ID()
}

type GetPostListRequest_CommunityID struct {
	CommunityID int64 `protobuf:"varint,2,opt,name=CommunityID,proto3,oneof"`
}

type GetPostListRequest_AuthorID struct {
	AuthorID int64 `protobuf:"varint,3,opt,name=AuthorID,proto3,oneof"`
}

func (*GetPostListRequest_CommunityID) isGetPostListRequest_ID() {}

func (*GetPostListRequest_AuthorID) isGetPostListRequest_ID() {}

func (m *GetPostListRequest) GetID() isGetPostListRequest_ID {
	if m != nil {
		return m.ID
	}
	return nil
}

func (m *GetPostListRequest) GetCommunityID() int64 {
	if x, ok := m.GetID().(*GetPostListRequest_CommunityID); ok {
		return x.CommunityID
	}
	return 0
}

func (m *GetPostListRequest) GetAuthorID() int64 {
	if x, ok := m.GetID().(*GetPostListRequest_AuthorID); ok {
		return x.AuthorID
	}
	return 0
}

func (m *GetPostListRequest) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetPostListRequest) GetMax() int64 {
	if m != nil {
		return m.Max
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*GetPostListRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*GetPostListRequest_CommunityID)(nil),
		(*GetPostListRequest_AuthorID)(nil),
	}
}

// Response:响应
type Response struct {
	// 响应
	Code                 int32             `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg                  string            `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	Data                 map[string]string `protobuf:"bytes,3,rep,name=Data,proto3" json:"Data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_e114ad14deab1dd1, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *Response) GetData() map[string]string {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterEnum("pbPost.GetPostListRequest_State", GetPostListRequest_State_name, GetPostListRequest_State_value)
	proto.RegisterType((*CreatePostRequest)(nil), "pbPost.CreatePostRequest")
	proto.RegisterType((*GetPostDetailRequest)(nil), "pbPost.GetPostDetailRequest")
	proto.RegisterType((*GetPostListRequest)(nil), "pbPost.GetPostListRequest")
	proto.RegisterType((*Response)(nil), "pbPost.Response")
	proto.RegisterMapType((map[string]string)(nil), "pbPost.Response.DataEntry")
}

func init() {
	proto.RegisterFile("post.proto", fileDescriptor_e114ad14deab1dd1)
}

var fileDescriptor_e114ad14deab1dd1 = []byte{
	// 399 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0xd1, 0x6e, 0x94, 0x50,
	0x10, 0xdd, 0xbb, 0xc0, 0xba, 0x4c, 0x53, 0x83, 0x93, 0xc6, 0x20, 0xe9, 0x03, 0xb9, 0x4f, 0xfb,
	0xc4, 0xc3, 0x9a, 0xa8, 0xa9, 0x4f, 0x15, 0x8c, 0x6e, 0x62, 0x93, 0xe6, 0xea, 0x0f, 0xdc, 0xa6,
	0x93, 0x4a, 0xa4, 0x5c, 0x84, 0xc1, 0xb8, 0x9f, 0xe2, 0xef, 0xf8, 0x21, 0x7e, 0x8b, 0xb9, 0x97,
	0x85, 0x4a, 0x5b, 0xdf, 0x66, 0x0e, 0x87, 0x73, 0x66, 0xe6, 0x1e, 0x80, 0xc6, 0x74, 0x9c, 0x35,
	0xad, 0x61, 0x83, 0xab, 0xe6, 0xea, 0xd2, 0x74, 0x2c, 0x09, 0x9e, 0xe5, 0x2d, 0x69, 0x26, 0xdb,
	0x29, 0xfa, 0xde, 0x53, 0xc7, 0x98, 0xc2, 0x51, 0x6e, 0x6e, 0x6f, 0xfb, 0xba, 0xe4, 0xfd, 0xae,
	0x88, 0x45, 0x2a, 0x36, 0x9e, 0xfa, 0x17, 0xc2, 0x13, 0x08, 0xbe, 0x94, 0x5c, 0x51, 0xbc, 0x4c,
	0xc5, 0x26, 0x54, 0x43, 0x83, 0x31, 0x3c, 0xc9, 0x4d, 0xcd, 0x54, 0x73, 0xec, 0x39, 0x7c, 0x6c,
	0x65, 0x06, 0x27, 0x1f, 0x88, 0xad, 0x47, 0x41, 0xac, 0xcb, 0x6a, 0x74, 0x7a, 0x0e, 0x2b, 0x0b,
	0x4e, 0x26, 0x87, 0x4e, 0xfe, 0x11, 0x80, 0x87, 0x1f, 0x3e, 0x95, 0x77, 0x83, 0xbd, 0x82, 0xe0,
	0xc2, 0x5c, 0x53, 0xe5, 0xd8, 0x4f, 0xb7, 0x69, 0x36, 0x6c, 0x91, 0x3d, 0xa4, 0x66, 0x9f, 0x59,
	0x33, 0xa9, 0x81, 0x8e, 0x72, 0xbe, 0x90, 0x1d, 0xda, 0xfb, 0xb8, 0x98, 0xaf, 0x74, 0x0a, 0xeb,
	0xf3, 0x9e, 0xbf, 0x9a, 0x76, 0x57, 0xb8, 0xe9, 0x2d, 0x61, 0x42, 0x10, 0xc1, 0xbf, 0xd4, 0x37,
	0x14, 0xfb, 0x6e, 0x4c, 0x57, 0x63, 0x04, 0xde, 0x85, 0xfe, 0x19, 0x07, 0x0e, 0xb2, 0xa5, 0x94,
	0x10, 0x38, 0x5f, 0x3c, 0x86, 0x70, 0xd2, 0x8e, 0x16, 0x08, 0xb0, 0x1a, 0x94, 0x22, 0xf1, 0xce,
	0x87, 0xe5, 0xae, 0x90, 0xbf, 0x04, 0xac, 0x15, 0x75, 0x8d, 0xa9, 0x3b, 0xb2, 0xe2, 0xb9, 0xb9,
	0x26, 0xb7, 0x55, 0xa0, 0x5c, 0xed, 0xc4, 0xbb, 0x9b, 0xc3, 0x7d, 0x6d, 0x89, 0x19, 0xf8, 0x85,
	0x66, 0x1d, 0x7b, 0xa9, 0xb7, 0x39, 0xda, 0x26, 0xe3, 0xee, 0xa3, 0x4a, 0x66, 0x3f, 0xbe, 0xaf,
	0xb9, 0xdd, 0x2b, 0xc7, 0x4b, 0x5e, 0x43, 0x38, 0x41, 0x56, 0xee, 0x1b, 0xed, 0x9d, 0x43, 0xa8,
	0x6c, 0x69, 0x9f, 0xf0, 0x87, 0xae, 0xfa, 0xe9, 0x09, 0x5d, 0x73, 0xb6, 0x7c, 0x23, 0xb6, 0xbf,
	0x05, 0xf8, 0x56, 0x1a, 0xcf, 0x60, 0x3d, 0x9e, 0x15, 0x93, 0xff, 0xdf, 0x3a, 0x89, 0xee, 0xcf,
	0x22, 0x17, 0xf8, 0x16, 0xe0, 0x2e, 0x58, 0xf8, 0x62, 0x64, 0x3c, 0x08, 0xdb, 0xa3, 0x3f, 0x9f,
	0xc3, 0xf1, 0x2c, 0x2e, 0x78, 0x7a, 0xcf, 0x7d, 0x96, 0xa2, 0xc7, 0x24, 0xae, 0x56, 0x2e, 0xe7,
	0x2f, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x1a, 0x12, 0x0a, 0x57, 0xf5, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// PostClient is the client API for Post service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PostClient interface {
	PostList(ctx context.Context, in *GetPostListRequest, opts ...grpc.CallOption) (*Response, error)
	CreatePost(ctx context.Context, in *CreatePostRequest, opts ...grpc.CallOption) (*Response, error)
	GetPostDetail(ctx context.Context, in *GetPostDetailRequest, opts ...grpc.CallOption) (*Response, error)
}

type postClient struct {
	cc grpc.ClientConnInterface
}

func NewPostClient(cc grpc.ClientConnInterface) PostClient {
	return &postClient{cc}
}

func (c *postClient) PostList(ctx context.Context, in *GetPostListRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/pbPost.Post/PostList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postClient) CreatePost(ctx context.Context, in *CreatePostRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/pbPost.Post/CreatePost", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *postClient) GetPostDetail(ctx context.Context, in *GetPostDetailRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/pbPost.Post/GetPostDetail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PostServer is the server API for Post service.
type PostServer interface {
	PostList(context.Context, *GetPostListRequest) (*Response, error)
	CreatePost(context.Context, *CreatePostRequest) (*Response, error)
	GetPostDetail(context.Context, *GetPostDetailRequest) (*Response, error)
}

// UnimplementedPostServer can be embedded to have forward compatible implementations.
type UnimplementedPostServer struct {
}

func (*UnimplementedPostServer) PostList(ctx context.Context, req *GetPostListRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PostList not implemented")
}
func (*UnimplementedPostServer) CreatePost(ctx context.Context, req *CreatePostRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePost not implemented")
}
func (*UnimplementedPostServer) GetPostDetail(ctx context.Context, req *GetPostDetailRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPostDetail not implemented")
}

func RegisterPostServer(s *grpc.Server, srv PostServer) {
	s.RegisterService(&_Post_serviceDesc, srv)
}

func _Post_PostList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServer).PostList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbPost.Post/PostList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServer).PostList(ctx, req.(*GetPostListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Post_CreatePost_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePostRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServer).CreatePost(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbPost.Post/CreatePost",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServer).CreatePost(ctx, req.(*CreatePostRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Post_GetPostDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPostDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PostServer).GetPostDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbPost.Post/GetPostDetail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PostServer).GetPostDetail(ctx, req.(*GetPostDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Post_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pbPost.Post",
	HandlerType: (*PostServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PostList",
			Handler:    _Post_PostList_Handler,
		},
		{
			MethodName: "CreatePost",
			Handler:    _Post_CreatePost_Handler,
		},
		{
			MethodName: "GetPostDetail",
			Handler:    _Post_GetPostDetail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "post.proto",
}
