// Code generated by protoc-gen-go. DO NOT EDIT.
// source: jwt.proto

package pbJwt

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type VerificationJWTResponse_StateOption int32

const (
	VerificationJWTResponse_NotPass            VerificationJWTResponse_StateOption = 0
	VerificationJWTResponse_Expired            VerificationJWTResponse_StateOption = 1
	VerificationJWTResponse_ExpiredJump        VerificationJWTResponse_StateOption = 2
	VerificationJWTResponse_MultiTerminalLogin VerificationJWTResponse_StateOption = 3
	VerificationJWTResponse_Pass               VerificationJWTResponse_StateOption = 4
)

var VerificationJWTResponse_StateOption_name = map[int32]string{
	0: "NotPass",
	1: "Expired",
	2: "ExpiredJump",
	3: "MultiTerminalLogin",
	4: "Pass",
}

var VerificationJWTResponse_StateOption_value = map[string]int32{
	"NotPass":            0,
	"Expired":            1,
	"ExpiredJump":        2,
	"MultiTerminalLogin": 3,
	"Pass":               4,
}

func (x VerificationJWTResponse_StateOption) String() string {
	return proto.EnumName(VerificationJWTResponse_StateOption_name, int32(x))
}

func (VerificationJWTResponse_StateOption) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b5cacc9c239fa0c7, []int{1, 0}
}

// =================== (中间件验证是否有效) ====================
type VerificationJWTRequest struct {
	Access               string   `protobuf:"bytes,1,opt,name=Access,proto3" json:"Access,omitempty" validate:"required"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerificationJWTRequest) Reset()         { *m = VerificationJWTRequest{} }
func (m *VerificationJWTRequest) String() string { return proto.CompactTextString(m) }
func (*VerificationJWTRequest) ProtoMessage()    {}
func (*VerificationJWTRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5cacc9c239fa0c7, []int{0}
}

func (m *VerificationJWTRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerificationJWTRequest.Unmarshal(m, b)
}
func (m *VerificationJWTRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerificationJWTRequest.Marshal(b, m, deterministic)
}
func (m *VerificationJWTRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerificationJWTRequest.Merge(m, src)
}
func (m *VerificationJWTRequest) XXX_Size() int {
	return xxx_messageInfo_VerificationJWTRequest.Size(m)
}
func (m *VerificationJWTRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerificationJWTRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerificationJWTRequest proto.InternalMessageInfo

func (m *VerificationJWTRequest) GetAccess() string {
	if m != nil {
		return m.Access
	}
	return ""
}

type VerificationJWTResponse struct {
	State                VerificationJWTResponse_StateOption `protobuf:"varint,1,opt,name=State,proto3,enum=pbJwt.VerificationJWTResponse_StateOption" json:"State,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                            `json:"-"`
	XXX_unrecognized     []byte                              `json:"-"`
	XXX_sizecache        int32                               `json:"-"`
}

func (m *VerificationJWTResponse) Reset()         { *m = VerificationJWTResponse{} }
func (m *VerificationJWTResponse) String() string { return proto.CompactTextString(m) }
func (*VerificationJWTResponse) ProtoMessage()    {}
func (*VerificationJWTResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5cacc9c239fa0c7, []int{1}
}

func (m *VerificationJWTResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerificationJWTResponse.Unmarshal(m, b)
}
func (m *VerificationJWTResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerificationJWTResponse.Marshal(b, m, deterministic)
}
func (m *VerificationJWTResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerificationJWTResponse.Merge(m, src)
}
func (m *VerificationJWTResponse) XXX_Size() int {
	return xxx_messageInfo_VerificationJWTResponse.Size(m)
}
func (m *VerificationJWTResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VerificationJWTResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VerificationJWTResponse proto.InternalMessageInfo

func (m *VerificationJWTResponse) GetState() VerificationJWTResponse_StateOption {
	if m != nil {
		return m.State
	}
	return VerificationJWTResponse_NotPass
}

type VerificationRefreshJWTRequest struct {
	Access               string   `protobuf:"bytes,1,opt,name=Access,proto3" json:"Access,omitempty" validate:"required"`
	Refresh              string   `protobuf:"bytes,2,opt,name=Refresh,proto3" json:"Refresh,omitempty" validate:"required"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VerificationRefreshJWTRequest) Reset()         { *m = VerificationRefreshJWTRequest{} }
func (m *VerificationRefreshJWTRequest) String() string { return proto.CompactTextString(m) }
func (*VerificationRefreshJWTRequest) ProtoMessage()    {}
func (*VerificationRefreshJWTRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5cacc9c239fa0c7, []int{2}
}

func (m *VerificationRefreshJWTRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerificationRefreshJWTRequest.Unmarshal(m, b)
}
func (m *VerificationRefreshJWTRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerificationRefreshJWTRequest.Marshal(b, m, deterministic)
}
func (m *VerificationRefreshJWTRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerificationRefreshJWTRequest.Merge(m, src)
}
func (m *VerificationRefreshJWTRequest) XXX_Size() int {
	return xxx_messageInfo_VerificationRefreshJWTRequest.Size(m)
}
func (m *VerificationRefreshJWTRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VerificationRefreshJWTRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VerificationRefreshJWTRequest proto.InternalMessageInfo

func (m *VerificationRefreshJWTRequest) GetAccess() string {
	if m != nil {
		return m.Access
	}
	return ""
}

func (m *VerificationRefreshJWTRequest) GetRefresh() string {
	if m != nil {
		return m.Refresh
	}
	return ""
}

type Response struct {
	// 响应
	Code                 int32             `protobuf:"varint,1,opt,name=Code,proto3" json:"Code,omitempty"`
	Msg                  string            `protobuf:"bytes,2,opt,name=Msg,proto3" json:"Msg,omitempty"`
	Data                 map[string]string `protobuf:"bytes,3,rep,name=Data,proto3" json:"Data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_b5cacc9c239fa0c7, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *Response) GetData() map[string]string {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterEnum("pbJwt.VerificationJWTResponse_StateOption", VerificationJWTResponse_StateOption_name, VerificationJWTResponse_StateOption_value)
	proto.RegisterType((*VerificationJWTRequest)(nil), "pbJwt.VerificationJWTRequest")
	proto.RegisterType((*VerificationJWTResponse)(nil), "pbJwt.VerificationJWTResponse")
	proto.RegisterType((*VerificationRefreshJWTRequest)(nil), "pbJwt.VerificationRefreshJWTRequest")
	proto.RegisterType((*Response)(nil), "pbJwt.Response")
	proto.RegisterMapType((map[string]string)(nil), "pbJwt.Response.DataEntry")
}

func init() {
	proto.RegisterFile("jwt.proto", fileDescriptor_b5cacc9c239fa0c7)
}

var fileDescriptor_b5cacc9c239fa0c7 = []byte{
	// 364 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0x4d, 0x4f, 0xc2, 0x40,
	0x10, 0xa5, 0xb4, 0xe5, 0x63, 0x9a, 0x48, 0x33, 0x31, 0x58, 0x49, 0x30, 0xa4, 0xf1, 0x40, 0x4c,
	0x6c, 0x0c, 0x1e, 0x34, 0x9e, 0x34, 0xca, 0xa5, 0x11, 0x95, 0x4a, 0x24, 0xf1, 0x56, 0x60, 0xc1,
	0x2a, 0xb4, 0xb5, 0xbb, 0x15, 0xf9, 0x27, 0xfe, 0x08, 0xef, 0xfe, 0x3d, 0xd3, 0xed, 0x8a, 0x08,
	0xa2, 0xb7, 0x79, 0xb3, 0xef, 0xed, 0xce, 0x9b, 0xb7, 0x50, 0x7c, 0x9c, 0x32, 0x2b, 0x8c, 0x02,
	0x16, 0xa0, 0x1a, 0xf6, 0xec, 0x29, 0x33, 0x0f, 0xa0, 0x7c, 0x47, 0x22, 0x6f, 0xe8, 0xf5, 0x5d,
	0xe6, 0x05, 0xbe, 0xdd, 0xed, 0x38, 0xe4, 0x39, 0x26, 0x94, 0x61, 0x19, 0x72, 0x67, 0xfd, 0x3e,
	0xa1, 0xd4, 0x90, 0x6a, 0x52, 0xbd, 0xe8, 0x08, 0x64, 0x7e, 0x48, 0xb0, 0xb5, 0x22, 0xa1, 0x61,
	0xe0, 0x53, 0x82, 0xa7, 0xa0, 0xde, 0x32, 0x97, 0x11, 0x2e, 0xd9, 0x68, 0xec, 0x59, 0xfc, 0x11,
	0x6b, 0x0d, 0xdd, 0xe2, 0xdc, 0xeb, 0x30, 0x69, 0x3b, 0xa9, 0xd0, 0xbc, 0x07, 0x6d, 0xa1, 0x8b,
	0x1a, 0xe4, 0xaf, 0x02, 0x76, 0xe3, 0x52, 0xaa, 0x67, 0x12, 0xd0, 0x7c, 0x0d, 0xbd, 0x88, 0x0c,
	0x74, 0x09, 0x4b, 0xa0, 0x09, 0x60, 0xc7, 0x93, 0x50, 0xcf, 0x62, 0x19, 0xb0, 0x15, 0x8f, 0x99,
	0xd7, 0x21, 0xd1, 0xc4, 0xf3, 0xdd, 0xf1, 0x65, 0x30, 0xf2, 0x7c, 0x5d, 0xc6, 0x02, 0x28, 0x5c,
	0xaf, 0x98, 0x6d, 0xa8, 0x2e, 0x4e, 0xe2, 0x90, 0x61, 0x44, 0xe8, 0xc3, 0xff, 0x96, 0xd1, 0x80,
	0xbc, 0x20, 0x1b, 0x59, 0x7e, 0xf0, 0x05, 0xcd, 0x37, 0x09, 0x0a, 0x73, 0xf7, 0x08, 0xca, 0x79,
	0x30, 0x48, 0xcd, 0xab, 0x0e, 0xaf, 0x51, 0x07, 0xb9, 0x45, 0x47, 0x42, 0x96, 0x94, 0xb8, 0x0f,
	0xca, 0x85, 0xcb, 0x5c, 0x43, 0xae, 0xc9, 0x75, 0xad, 0xb1, 0x2d, 0x56, 0x34, 0xdf, 0x49, 0x72,
	0xd6, 0xf4, 0x59, 0x34, 0x73, 0x38, 0xad, 0x72, 0x04, 0xc5, 0x79, 0x2b, 0xb9, 0xed, 0x89, 0xcc,
	0xc4, 0x74, 0x49, 0x89, 0x9b, 0xa0, 0xbe, 0xb8, 0xe3, 0x98, 0x88, 0x17, 0x52, 0x70, 0x92, 0x3d,
	0x96, 0x1a, 0xef, 0x12, 0xc8, 0x76, 0xb7, 0x83, 0xed, 0x9f, 0x09, 0x7f, 0xbb, 0xc6, 0xdd, 0x5f,
	0xe2, 0x59, 0x59, 0x4a, 0xa5, 0xb4, 0x34, 0xa1, 0x99, 0x41, 0x07, 0x4a, 0x4b, 0x91, 0x62, 0x75,
	0x5d, 0xd4, 0xe9, 0x25, 0x3b, 0x7f, 0xff, 0x04, 0x33, 0xd3, 0xcb, 0xf1, 0x6f, 0x79, 0xf8, 0x19,
	0x00, 0x00, 0xff, 0xff, 0xec, 0xa6, 0x4e, 0x94, 0xa3, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// JWTClient is the client API for JWT service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type JWTClient interface {
	VerificationRefreshJWT(ctx context.Context, in *VerificationRefreshJWTRequest, opts ...grpc.CallOption) (*Response, error)
	VerificationJWT(ctx context.Context, in *VerificationJWTRequest, opts ...grpc.CallOption) (*VerificationJWTResponse, error)
}

type jWTClient struct {
	cc grpc.ClientConnInterface
}

func NewJWTClient(cc grpc.ClientConnInterface) JWTClient {
	return &jWTClient{cc}
}

func (c *jWTClient) VerificationRefreshJWT(ctx context.Context, in *VerificationRefreshJWTRequest, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/pbJwt.JWT/VerificationRefreshJWT", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *jWTClient) VerificationJWT(ctx context.Context, in *VerificationJWTRequest, opts ...grpc.CallOption) (*VerificationJWTResponse, error) {
	out := new(VerificationJWTResponse)
	err := c.cc.Invoke(ctx, "/pbJwt.JWT/VerificationJWT", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// JWTServer is the server API for JWT service.
type JWTServer interface {
	VerificationRefreshJWT(context.Context, *VerificationRefreshJWTRequest) (*Response, error)
	VerificationJWT(context.Context, *VerificationJWTRequest) (*VerificationJWTResponse, error)
}

// UnimplementedJWTServer can be embedded to have forward compatible implementations.
type UnimplementedJWTServer struct {
}

func (*UnimplementedJWTServer) VerificationRefreshJWT(ctx context.Context, req *VerificationRefreshJWTRequest) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerificationRefreshJWT not implemented")
}
func (*UnimplementedJWTServer) VerificationJWT(ctx context.Context, req *VerificationJWTRequest) (*VerificationJWTResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerificationJWT not implemented")
}

func RegisterJWTServer(s *grpc.Server, srv JWTServer) {
	s.RegisterService(&_JWT_serviceDesc, srv)
}

func _JWT_VerificationRefreshJWT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerificationRefreshJWTRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JWTServer).VerificationRefreshJWT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbJwt.JWT/VerificationRefreshJWT",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JWTServer).VerificationRefreshJWT(ctx, req.(*VerificationRefreshJWTRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _JWT_VerificationJWT_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerificationJWTRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(JWTServer).VerificationJWT(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbJwt.JWT/VerificationJWT",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(JWTServer).VerificationJWT(ctx, req.(*VerificationJWTRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _JWT_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pbJwt.JWT",
	HandlerType: (*JWTServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VerificationRefreshJWT",
			Handler:    _JWT_VerificationRefreshJWT_Handler,
		},
		{
			MethodName: "VerificationJWT",
			Handler:    _JWT_VerificationJWT_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "jwt.proto",
}
